### ISSUE TITLE
re-positioning

### ISSUE THREAD

**Issue by nise** [dmitriyfiction/clipping-demo#1]
Would it be possible to align the video fragment to the left and top. Furthermore, I would expect the control bars right below the clip. At the end the clip should appear as self-contained video.

**Comment by nise** [comment]
For re-positioning some css-command should be sufficient.

**Comment by nise** [comment]
Now the video is in the right place but if I want to put it inside a div that has a fixed max-width and max-width the video is overlapping. An application example would be a preview list of extracted video fragments beside the main video. Each fragment in the list has a title and a short description.

**Comment by dmitriyfiction** [comment]
@nise I just fixed all bugs, which seemed to be there. Take a look.

**Comment by nise** [comment]
I do not see any changes. The video fragment is still placed at its origin and not at the bottom left corner or somewhere outside. Maybe this is an issue between Ubuntu and Windows, but Chrome and Firefox.
I have send you some screenshots.

**Comment by dmitriyfiction** [comment]
@nise You can change the position of the video by changing first two parameters of the function, I sent a new commit where I changed them slightly and the video moved. In the first comment in this issue you asked me to use top and left coordinates of the video, so I used top and left (not bottom and left).

**Comment by nise** [comment]
@dmitriyfiction I see it appears at the right place now by using absolute positioning. If I try to have some text above the video the text will be overlapped. 

`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>clipping demo</title>
  <link type="text/css" href="css/style.css" rel="stylesheet">
</head>

<body>

<div class="container">
  <h3>Hello</h3>
  <div class="video-player clearfix">

    <div class="video-outer-wrapper">

      <div class="video-inner-wrapper">
        <video class="video-element" width="480" height="280" controls autoplay crossorigin="anonymous">
          <source src="http://simpl.info/track/video/developerStories-en.webm" type='video/webm; codecs="vp8, vorbis"'>
          Your browser does not support the video tag.
        </video>
      </div>
    </div>

    <div class="controls">Controls</div>

  </div>

</div>

<script src="src/clipping.js"></script>

</body>
</html>`

**Comment by dmitriyfiction** [comment]
@nise You have to add any elements inside the video-outer-wrapper and they will be shown. It is so, because you wanted to also move the position of the whole block of the video (last 2 params).

**Comment by dmitriyfiction** [comment]
I guess the problem was solved, so I close this issue
